push:
  branch:
    prefix: feat
    name: test-foundations
  commit:
    firstLine: "test: scaffold vitest harness"
    body: |
      Introduce Vitest runner scripts, shared test setup utilities, and baseline unit specs.
      Locks current behaviors to support upcoming object-oriented refactors.
